version: "3.9"

services:
  mongo:
    image: mongo:4.4.11
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes: 
      - ./bitmex_db:/var/lib/mongo

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345
      ME_CONFIG_MONGODB_URL: mongodb://mongo:12345@mongo:27017/
    depends_on:
      - mongo

  mexmine:
    build:
      context: ./
      dockerfile: mexmine.Dockerfile
    restart: always
    depends_on:
      - mongo
      - mongo-express
    volumes:
     - ./dump:/mexmine/dump
     - ./logs:/mexmine/logs
