version: "3.9"

services:
  mongo:
    image: mongo:4.4.11
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: your user here
      MONGO_INITDB_ROOT_PASSWORD: your pass here
    volumes: 
      - /var/bitmex_db:/var/lib/mongo

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: your user here
      ME_CONFIG_MONGODB_ADMINPASSWORD: your password here
      ME_CONFIG_MONGODB_URL: mongodb://youruserhere:yourpasswordhere@mongo:27017/
    depends_on:
      - mongo
